/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2026 Alessandro Mattos
 */

using Gee;

namespace Purrify {
    // One target at a time. Waiting for a giant final list makes the app feel dead.
    public delegate void TargetFoundCallback (CleaningTarget target);

    public class Scanner : Object {
        private string home_dir;

        public Scanner () {
            home_dir = Environment.get_home_dir ();
        }

        public void scan (ScanOptions options, TargetFoundCallback on_found) {
            if (options.include_apps_cache) {
                add_known_path_target (
                    on_found,
                    "thumbnails-cache",
                    _("Thumbnails cache"),
                    _("Cached image previews generated by file managers and apps."),
                    Path.build_filename (home_dir, ".cache", "thumbnails"),
                    true,
                    false,
                    "image-x-generic-symbolic"
                );

                add_crash_reports (on_found);
                add_dev_tool_caches (on_found);
            }

            if (options.include_folders) {
                add_known_path_target (
                    on_found,
                    "trash-files",
                    _("Trash files"),
                    _("Files currently stored in your local Trash folder."),
                    Path.build_filename (home_dir, ".local", "share", "Trash", "files"),
                    true,
                    false,
                    "user-trash-symbolic"
                );

                add_known_path_target (
                    on_found,
                    "trash-info",
                    _("Trash metadata"),
                    _("Metadata used by the local Trash folder."),
                    Path.build_filename (home_dir, ".local", "share", "Trash", "info"),
                    true,
                    false,
                    "user-trash-symbolic"
                );

                if (options.include_duplicates) {
                    add_duplicate_downloads (on_found);
                }

                add_empty_folders (on_found);
                add_broken_shortcuts (on_found);
            }
        }

        private void add_known_path_target (
            TargetFoundCallback on_found,
            string id,
            string title,
            string description,
            string path,
            bool selected_by_default = true,
            bool skip_if_empty = false,
            string icon_name = "folder-symbolic",
            string category = ""
        ) {
            uint64 size = 0;

            if (FileUtils.path_exists (path)) {
                size = FileUtils.directory_size (path);
            }

            if (skip_if_empty && size == 0) {
                return;
            }

            var target = new CleaningTarget.remove_path (
                id, title, description, path, size, selected_by_default, icon_name
            );
            target.category = category;
            on_found (target);
        }

        private void add_dev_tool_caches (TargetFoundCallback on_found) {
            add_known_path_target (
                on_found,
                "dev-cache-pip",
                _("Python package cache (pip)"),
                _("Downloaded Python packages pip already installed. pip re-downloads them if needed again."),
                Path.build_filename (home_dir, ".cache", "pip"),
                false,
                true,
                "applications-development-symbolic",
                _("Developer tool caches")
            );

            add_known_path_target (
                on_found,
                "dev-cache-npm",
                _("Node package cache (npm)"),
                _("Downloaded Node.js packages npm already installed. npm re-downloads them if needed again."),
                Path.build_filename (home_dir, ".npm", "_cacache"),
                false,
                true,
                "applications-development-symbolic",
                _("Developer tool caches")
            );

            add_known_path_target (
                on_found,
                "dev-cache-yarn",
                _("Node package cache (Yarn)"),
                _("Downloaded Node.js packages Yarn already installed. Yarn re-downloads them if needed again."),
                Path.build_filename (home_dir, ".cache", "yarn"),
                false,
                true,
                "applications-development-symbolic",
                _("Developer tool caches")
            );
        }

        private void add_crash_reports (TargetFoundCallback on_found) {
            string cache_dir = Path.build_filename (home_dir, ".cache");
            var cache = File.new_for_path (cache_dir);

            if (!cache.query_exists ()) {
                return;
            }

            try {
                FileEnumerator enumerator = cache.enumerate_children (
                    "standard::name,standard::type",
                    FileQueryInfoFlags.NOFOLLOW_SYMLINKS
                );

                FileInfo? info;
                while ((info = enumerator.next_file ()) != null) {
                    if (info.get_file_type () != FileType.DIRECTORY) {
                        continue;
                    }

                    string app_folder = info.get_name ();
                    string crash_path = Path.build_filename (cache_dir, app_folder, "Crash Reports");

                    if (!FileUtils.path_exists (crash_path)) {
                        continue;
                    }

                    uint64 size = FileUtils.directory_size (crash_path);

                    if (size == 0) {
                        continue;
                    }

                    var target = new CleaningTarget.remove_path (
                        "crash-reports-" + app_folder,
                        _("Crash reports: %s").printf (app_folder),
                        _("Diagnostic crash dumps left behind by an app. Safe to remove; only useful for debugging that app."),
                        crash_path,
                        size,
                        true,
                        "dialog-warning-symbolic"
                    );
                    target.category = _("Crash reports");
                    on_found (target);
                }
            } catch (Error error) {
                // Crash reports are a bonus round. If this fails, keep scanning.
            }
        }

        // Duplicate names lie. Hashes snitch.

        private const uint64 DUPLICATE_SCAN_MAX_FILE_SIZE = 200 * 1024 * 1024;
        private const int DUPLICATE_SCAN_MAX_DEPTH = 6;
        private const int DUPLICATE_SCAN_MAX_RESULTS = 200;

        private void add_duplicate_downloads (TargetFoundCallback on_found) {
            string downloads_dir = Environment.get_user_special_dir (UserDirectory.DOWNLOAD);
            if (downloads_dir == null) {
                return;
            }

            var dir = File.new_for_path (downloads_dir);
            if (!dir.query_exists ()) {
                return;
            }

            var by_size = new HashMap<string, ArrayList<string>> ();

            try {
                collect_files_by_size (dir, by_size, 0);
            } catch (Error error) {
                return;
            }

            int emitted = 0;

            foreach (var size_group in by_size.values) {
                if (size_group.size < 2) {
                    continue;
                }

                if (emitted >= DUPLICATE_SCAN_MAX_RESULTS) {
                    break;
                }

                var by_hash = new HashMap<string, ArrayList<string>> ();

                foreach (string file_path in size_group) {
                    string? hash = hash_file (file_path);

                    if (hash == null) {
                        continue;
                    }

                    if (!by_hash.has_key (hash)) {
                        by_hash.set (hash, new ArrayList<string> ());
                    }

                    by_hash.get (hash).add (file_path);
                }

                foreach (var hash_group in by_hash.values) {
                    if (hash_group.size < 2) {
                        continue;
                    }

                    if (emitted >= DUPLICATE_SCAN_MAX_RESULTS) {
                        break;
                    }

                    string keep_path = oldest_file (hash_group);

                    foreach (string duplicate_path in hash_group) {
                        if (emitted >= DUPLICATE_SCAN_MAX_RESULTS) {
                            break;
                        }

                        if (duplicate_path == keep_path) {
                            continue;
                        }

                        uint64 size = FileUtils.directory_size (duplicate_path);

                        var target = new CleaningTarget.remove_path (
                            "duplicate-" + duplicate_path,
                            _("Duplicate: %s").printf (Path.get_basename (duplicate_path)),
                            _("Identical to %s, already in Downloads. This check can be slow on large folders, so duplicates are left unselected for review.").printf (Path.get_basename (keep_path)),
                            duplicate_path,
                            size,
                            false,
                            "edit-copy-symbolic"
                        );
                        target.category = _("Duplicate files");
                        on_found (target);
                        emitted++;
                    }
                }
            }
        }

        private void collect_files_by_size (
            File dir,
            HashMap<string, ArrayList<string>> by_size,
            int depth
        ) throws Error {
            if (depth > DUPLICATE_SCAN_MAX_DEPTH) {
                return;
            }

            FileEnumerator enumerator = dir.enumerate_children (
                "standard::name,standard::type,standard::size",
                FileQueryInfoFlags.NOFOLLOW_SYMLINKS
            );

            FileInfo? info;
            while ((info = enumerator.next_file ()) != null) {
                var child = dir.get_child (info.get_name ());

                if (info.get_file_type () == FileType.DIRECTORY) {
                    collect_files_by_size (child, by_size, depth + 1);
                    continue;
                }

                if (info.get_file_type () != FileType.REGULAR) {
                    continue;
                }

                uint64 size = info.get_size ();

                if (size == 0 || size > DUPLICATE_SCAN_MAX_FILE_SIZE) {
                    continue;
                }

                string key = size.to_string ();

                if (!by_size.has_key (key)) {
                    by_size.set (key, new ArrayList<string> ());
                }

                by_size.get (key).add (child.get_path ());
            }
        }

        private string? hash_file (string path) {
            try {
                var stream = File.new_for_path (path).read ();
                var checksum = new Checksum (ChecksumType.SHA256);
                uint8[] buffer = new uint8[65536];
                ssize_t read_count;

                while ((read_count = stream.read (buffer)) > 0) {
                    checksum.update (buffer[0:read_count], read_count);
                }

                return checksum.get_string ();
            } catch (Error error) {
                return null;
            }
        }

        private string oldest_file (ArrayList<string> paths) {
            string oldest = paths[0];
            int64 oldest_mtime = file_mtime (oldest);

            foreach (string path in paths) {
                int64 mtime = file_mtime (path);

                if (mtime < oldest_mtime) {
                    oldest_mtime = mtime;
                    oldest = path;
                }
            }

            return oldest;
        }

        private int64 file_mtime (string path) {
            try {
                var info = File.new_for_path (path).query_info (
                    "time::modified",
                    FileQueryInfoFlags.NOFOLLOW_SYMLINKS
                );
                var modified = info.get_modification_date_time ();
                return modified != null ? modified.to_unix () : 0;
            } catch (Error error) {
                return 0;
            }
        }

        // Only scan the obvious surface folders. Whole-home spelunking is how cleaners
        // become villains.

        private const int SURFACE_SCAN_MAX_DEPTH = 6;

        private string[] get_surface_scan_roots () {
            string[] roots = {};

            string? downloads = Environment.get_user_special_dir (UserDirectory.DOWNLOAD);
            string? desktop = Environment.get_user_special_dir (UserDirectory.DESKTOP);
            string? documents = Environment.get_user_special_dir (UserDirectory.DOCUMENTS);

            if (downloads != null) {
                roots += downloads;
            }

            if (desktop != null) {
                roots += desktop;
            }

            if (documents != null) {
                roots += documents;
            }

            return roots;
        }

        private void add_empty_folders (TargetFoundCallback on_found) {
            foreach (string root_path in get_surface_scan_roots ()) {
                var root = File.new_for_path (root_path);

                if (!root.query_exists ()) {
                    continue;
                }

                try {
                    find_empty_folders (root, on_found, 0);
                } catch (Error error) {
                    // Not worth stopping the scan for an empty-folder tantrum.
                }
            }
        }

        private void find_empty_folders (
            File dir,
            TargetFoundCallback on_found,
            int depth
        ) throws Error {
            if (depth > SURFACE_SCAN_MAX_DEPTH) {
                return;
            }

            FileEnumerator enumerator = dir.enumerate_children (
                "standard::name,standard::type",
                FileQueryInfoFlags.NOFOLLOW_SYMLINKS
            );

            var children = new ArrayList<FileInfo> ();
            FileInfo? info;
            while ((info = enumerator.next_file ()) != null) {
                children.add (info);
            }

            if (children.size == 0) {
                string path = dir.get_path ();

                var target = new CleaningTarget.remove_path (
                    "empty-folder-" + path,
                    _("Empty folder: %s").printf (Path.get_basename (path)),
                    _("Leftover empty folder, likely from an extracted or moved download."),
                    path,
                    0,
                    true,
                    "folder-symbolic",
                    true
                );
                target.category = _("Empty folders");
                on_found (target);

                return;
            }

            foreach (var child_info in children) {
                if (child_info.get_file_type () == FileType.DIRECTORY) {
                    find_empty_folders (dir.get_child (child_info.get_name ()), on_found, depth + 1);
                }
            }
        }

        private void add_broken_shortcuts (TargetFoundCallback on_found) {
            foreach (string root_path in get_surface_scan_roots ()) {
                var root = File.new_for_path (root_path);

                if (!root.query_exists ()) {
                    continue;
                }

                try {
                    find_broken_shortcuts (root, on_found, 0);
                } catch (Error error) {
                    // Broken shortcuts are cleanup garnish. Keep moving if this fails.
                }
            }
        }

        private void find_broken_shortcuts (
            File dir,
            TargetFoundCallback on_found,
            int depth
        ) throws Error {
            if (depth > SURFACE_SCAN_MAX_DEPTH) {
                return;
            }

            FileEnumerator enumerator = dir.enumerate_children (
                "standard::name,standard::type,standard::is-symlink",
                FileQueryInfoFlags.NOFOLLOW_SYMLINKS
            );

            FileInfo? info;
            while ((info = enumerator.next_file ()) != null) {
                var child = dir.get_child (info.get_name ());

                if (info.get_is_symlink ()) {
                    // query_exists() follows symlinks. False means the target is gone.
                    if (!child.query_exists ()) {
                        string path = child.get_path ();

                        var target = new CleaningTarget.remove_path (
                            "broken-shortcut-" + path,
                            _("Broken shortcut: %s").printf (Path.get_basename (path)),
                            _("A shortcut pointing to a file or folder that no longer exists."),
                            path,
                            0,
                            true,
                            "folder-symbolic",
                            true
                        );
                        target.category = _("Broken shortcuts");
                        on_found (target);
                    }

                    continue;
                }

                if (info.get_file_type () == FileType.DIRECTORY) {
                    find_broken_shortcuts (child, on_found, depth + 1);
                }
            }
        }
    }
}
